### ISSUE TITLE
Custom 404 pages needed

### ISSUE THREAD

**Issue by safestackhq** [SafeStack/ava#108]
In a few places we use the built in method get_object_or_404 to return the requested object.

If this fails we get the standard yellow Django 404 page. While this is functional it's not exactly pretty or useful.

We need a custom 404 page designed and tested throughout to ensure that if the user triggers a 404, they know what to do next

**Comment by tveastman** [comment]
The yellow django 404 and 500 messages are a feature of Django's DEBUG mode. When debug mode is turned off, Django will use different 404 and 500 views and templates.

Turning DEBUG off requires a few other tweaks as well that haven't been sorted out yet (static files will no longer be hosted, for example). But when it is, the 'dh5bp' app has some reasonably-nicely styled default 404 and 500 pages.

**Comment by tveastman** [comment]
When merged, pull request 122 adds two templates in ava/templates/dh5bp that override the default dh5bp ones and can be used to create AVA branded 404/500 pages when the DEBUG mode is turned off, however that still has a dependency on graceful handling of static assets when debug mode is turned off, which isn't sorted out in the developer docker setup.
